services:
  robot-game:
    image: joaonunovalente/robot-game
    ports:
      - 8000:8000
    container_name: robot-game

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower